# Generated by Django 5.2.6 on 2025-09-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='location',
            field=models.CharField(blank=True, help_text='Where the item was found', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='location',
            field=models.CharField(blank=True, help_text='Where the item was lost', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
