# Generated by Django 5.2.6 on 2025-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_founditem_location_founditem_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to='found_item_images/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_item_images/'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Smartwatch', 'Smartwatch'), ('Earbuds / Headphones', 'Earbuds / Headphones'), ('Camera', 'Camera'), ('Other electronics', 'Other electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Smartwatch', 'Smartwatch'), ('Earbuds / Headphones', 'Earbuds / Headphones'), ('Camera', 'Camera'), ('Other electronics', 'Other electronics')], max_length=100),
        ),
    ]
