# Generated by Django 5.2.6 on 2025-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_founditem_device_image_lostitem_device_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='reporter_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='reporter_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='address_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='city_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='lost_item_receipts/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='reporter_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='reporter_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='time_found',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
