# Generated by Django 5.2.6 on 2025-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_founditem_address_founditem_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitem',
            old_name='description',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='reporter_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='device_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='reporter_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='receipt',
            new_name='recepiet',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='device',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='name',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='title',
            field=models.CharField(default='Untitled', max_length=150),
            preserve_default=False,
        ),
    ]
