# Generated by Django 5.2.6 on 2025-09-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_rename_description_lostitem_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='color',
        ),
    ]
