# Generated by Django 5.2.6 on 2025-09-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_remove_founditem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='founder_email',
            field=models.EmailField(blank=True, help_text='Email of the person who found the item', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='loster_email',
            field=models.EmailField(blank=True, help_text='Email of the person who lost the item', max_length=254, null=True),
        ),
    ]
