# Generated by Django 5.2.6 on 2025-09-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_founditem_founder_email_lostitem_loster_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(default='unclaimed', max_length=50),
        ),
    ]
