# Generated by Django 5.2.6 on 2025-09-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_return_claimed_at_return_claimed_by_return_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed')], db_index=True, default='unclaimed', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('lost_item', 'found_item')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_status'], name='devices_mat_match_s_69e939_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['lost_item', 'found_item'], name='devices_mat_lost_it_db1335_idx'),
        ),
    ]
