# Generated by Django 5.2.6 on 2025-09-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_return_finder_email_return_finder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='founder_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='founder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='founder_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loster_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loster_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loster_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
