# Generated by Django 5.2.6 on 2025-09-28 18:12

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_match_device_name_match_founder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='device_images/'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='device_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='found_item_images/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='lost_item_images/'),
        ),
    ]
